default_config:
cloud:

mbweather:
  host: !secret mbweather_ip
  username: !secret mbweather_user
  password: !secret mbweather_pass

binary_sensor:
  - platform: mbweather

sensor:
  - platform: mbweather

weather:
  - platform: mbweather
    api_key: !secret ds_api_key
    mode: daily
    name: Vindinge

logger:
  default: error
  logs:
    custom_components.mbweather: debug
